
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "PxLDevApp.h"
#include "DevAppPage.h"
#include "LookupGraph.h"

/////////////////////////////////////////////////////////////////////////////
// CLookupGraph

IMPLEMENT_DYNCREATE(CLookupGraph, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CLookupGraph properties

/////////////////////////////////////////////////////////////////////////////
// CLookupGraph operations
BEGIN_MESSAGE_MAP(CLookupGraph, CWnd)
	ON_WM_HELPINFO()
END_MESSAGE_MAP()


BOOL CLookupGraph::OnHelpInfo(HELPINFO* pHelpInfo)
{
	CDevAppPage* pPage = static_cast<CDevAppPage*>(this->GetParent());
	if (pPage->IsKindOf(RUNTIME_CLASS(CDevAppPage)))
		return pPage->OnHelpInfo(pHelpInfo);

//	return CWnd::OnHelpInfo(pHelpInfo);
	return FALSE;
}
