#//
#// Capture OEM Controls
#//
#// Build Capture OEM's Active X control
#//
SOLUTION=PxLControls
!include $(BUILD_TOOLS)\makefile.vs08

#//
#// Build everything
#//
build:
	@$(MAKE) clean_build_tidyup




